<a href="https://colab.research.google.com/github/liupengzhouyi/DeepLearning/blob/main/pytorch_2023_001_%E9%87%8D%E6%96%B0%E5%85%A5%E9%97%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-6.1102e-27,  4.5757e-41, -6.1102e-27],
        [ 4.5757e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -2.0177e-28]])


In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.3496, 0.5865, 0.8200],
        [0.9463, 0.8897, 0.8445],
        [0.1606, 0.7630, 0.4598],
        [0.4254, 0.5049, 0.3874],
        [0.3200, 0.0848, 0.7389]])


In [6]:
print(torch.add(x, y))

tensor([[0.3496, 0.5865, 0.8200],
        [0.9463, 0.8897, 0.8445],
        [0.1606, 0.7630, 0.4598],
        [0.4254, 0.5049, 0.3874],
        [0.3200, 0.0848, 0.7389]])


In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.3496, 0.5865, 0.8200],
        [0.9463, 0.8897, 0.8445],
        [0.1606, 0.7630, 0.4598],
        [0.4254, 0.5049, 0.3874],
        [0.3200, 0.0848, 0.7389]])


In [8]:
y.add_(x)
print(y)

tensor([[0.3496, 0.5865, 0.8200],
        [0.9463, 0.8897, 0.8445],
        [0.1606, 0.7630, 0.4598],
        [0.4254, 0.5049, 0.3874],
        [0.3200, 0.0848, 0.7389]])


In [9]:
print(x[:, 1])

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00])


In [10]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    # x + y
    print(x + y)

tensor([[0.3496, 0.5865, 0.8200],
        [0.9463, 0.8897, 0.8445],
        [0.1606, 0.7630, 0.4598],
        [0.4254, 0.5049, 0.3874],
        [0.3200, 0.0848, 0.7389]], device='cuda:0')


In [18]:
import torch
from torch.autograd import Variable

In [19]:
x1 = Variable(torch.ones(2, 2), requires_grad=True)
print(x1)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
y2 = x1 + 2
print(y2)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [26]:
print(y2.grad_fn)

In [32]:
z = y2 * y2 * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [33]:
out.backward()

In [34]:
print(x1.grad)

tensor([[9., 9.],
        [9., 9.]])


In [35]:
print(x1.data)
print(y2.data)
print(z.data)

tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[27., 27.],
        [27., 27.]])


In [38]:
print(x1.grad)
print(y2.grad)
# print(z.grad)

tensor([[9., 9.],
        [9., 9.]])
None


<ipython-input-38-65fbd2a708bc>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  print(y2.grad)


In [39]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  990.0938, -1329.9825,   280.9055], grad_fn=<MulBackward0>)


In [40]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [41]:
params = list(net.parameters())
print(len(params))
print(params[0].size()) 


10
torch.Size([6, 1, 5, 5])


In [42]:
input = Variable(torch.randn(1, 1, 32, 32))
out = net(input)
print(out)

tensor([[-0.0024, -0.0888,  0.0721,  0.1170, -0.1354, -0.0635, -0.0366, -0.0598,
          0.0447, -0.0684]], grad_fn=<AddmmBackward0>)
